version: 2.1
aliases:
  - &restore-cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "gradle.properties" }}
        - v1-dependencies-
  - &save-cache
    save_cache:
      paths:
        - ~/.gradle/wrapper
        - ~/.gradle/caches
      key: v1-dependencies-{{ checksum "gradle.properties" }}


  - &defaults
    docker:
      - image: cimg/openjdk:11.0

commands:
  run-with-dependencies:
    parameters:
      steps:
        description: "Steps that will be executed after loading dependencies"
        type: steps
    steps:
      - checkout
      - *restore-cache
      - steps: << parameters.steps >>

jobs:
  create-cache:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - run: ./gradlew dependencies
      - *save-cache
  build:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew assemble --info
  tests:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew test coveralls --info
  lint:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew ktlintCheck --info
  release:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "81:f3:60:9a:cf:e7:f7:c0:7c:1d:f9:2f:90:12:e7:df"
            - run: git config user.email "circle-ci@pipeline.com"
            - run: git config user.name "Circle CI"
            - run: RELEASE_VERSION=$(echo $CIRCLE_BRANCH | cut -f2 -d-)
            - run: ./gradlew core:release -Prelease.useAutomaticVersion=true -Prelease.version=$RELEASE_VERSION

workflows:
  version: 2.1
  build-test-verify-deploy:
    jobs:
      - create-cache
      - build:
          requires:
            - create-cache
      - tests:
          requires:
            - create-cache
      - lint:
          requires:
            - create-cache
      - release:
          requires:
            - build
            - tests
            - lint
          filters:
            branches:
              only:
                - /^release-.*$/

