# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
aliases:
  - &restore-cache
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "core-java-tests/build.gradle" }}
          - v1-dependencies-
  - &save-cache
    - save_cache:
        paths:
          - ~/.gradle
          - ./.gradle
        key: v1-dependencies--{{ checksum "build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "core-java-tests/build.gradle" }}

  - &dependencies
    - checkout
    - *restore-cache
    - ./gradlew dependencies --info
    - *save-cache
  - &base-java-image
    - docker:
        - image: cimg/openjdk:11.0

jobs:
  build:
    *base-java-image
    steps:
      - *dependencies
      - run: ./gradlew test --info
  lint:
    *base-java-image
    steps:
      - *dependencies
      - run: ./gradlew ktlintCheck --info

workflows:
  version: 2
  test_and_validate:
    jobs:
      - test
      - lint

