version: 2.1
aliases:
  - &restore-cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "core-java-tests/build.gradle" }}
        - v1-dependencies-
  - &save-cache
    save_cache:
      paths:
        - ./.gradle
        - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "core-java-tests/build.gradle" }}


  - &defaults
    docker:
      - image: cimg/openjdk:11.0

commands:
  run-with-dependencies:
    parameters:
      steps:
        description: "Steps that will be executed after loading dependencices"
        type: steps
    steps:
      - checkout
      - *restore-cache
      - steps: << parameters.steps >>

jobs:
  create-cache:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - run: ./gradlew dependencies
      - *save-cache
  build:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew assemble --info
  tests:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew test --info
  lint:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew ktlintCheck --info
workflows:
  version: 2.1
  build-test-verify-deploy:
    jobs:
      - create-cache
      - build:
          requires:
            - create-cache
      - tests:
          requires:
            - create-cache
      - lint:
          requires:
            - create-cache

