version: 2.1
aliases:
  - &dependencies-path
      v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "core/build.gradle" }}-{{ checksum "core-java-tests/build.gradle" }}

  - &restore-cache
    restore_cache:
      keys:
        - *dependencies-path
        - v1-dependencies-
  - &save-cache
    save_cache:
      paths:
        - ./.gradle
      key: *dependencies-path

  - &defaults
    docker:
      - image: cimg/openjdk:11.0

commands:
  run-with-dependencies:
    parameters:
      steps:
        description: "Steps that will be executed after loading dependencices"
        type: steps
    steps:
      - checkout
      - *restore-cache
      - steps: << parameters.steps >>

jobs:
  create-cache:
    <<: *defaults
    steps:
      - checkout
      - run: ./gradlew dependencies
      - *save-cache
  build:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew assemble --info
  tests:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew test --info
  lint:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew ktlintCheck --info
workflows:
  version: 2.1
  create-cache:
    jobs:
      - create-cache
  test-and-verify:
    jobs:
      - build
      - tests
      - lint

