version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: ./gradlew test --info
  lint:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run: ./gradlew ktlintCheck --info

workflows:
  version: 2.1
  test_and_verify:
    jobs:
      - tests
      - lint

